image: maven:3.8.4-openjdk-17

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn clean test

before_script:
  - mvn --version